#!/usr/bin/env python3
"""Verify PACKAGE_MANIFEST.sha256 across LF/CRLF checkouts.

Git can normalize text line endings differently on Windows and Linux. For files
without NUL bytes, verification therefore accepts the raw-byte digest as well as
digests of LF-normalized and CRLF-normalized content. Binary files remain
strictly byte-for-byte verified.
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "PACKAGE_MANIFEST.sha256"
# These paths are deliberately generated outside the distributable source
# package.  They can exist in a developer checkout after a smoke test or a
# public-data validation run, but must not make the release manifest fail (or
# force us to hash private/raw image outputs into the source package).
EXCLUDED = {
    Path("PACKAGE_MANIFEST.sha256"),
    Path(".DS_Store"),
}
GENERATED_DIRS = {
    # Developer-local R package library; it is ignored by Git and must never
    # be required in the distributable source manifest.
    "Rlib",
    "work",
    "tests/synthetic_output",
    "tests/synthetic_if_output",
    "tests/synthetic_coloc_output",
    "tests/synthetic_puncta_output",
    # IF/advanced fixture TIFFs are generated by the smoke-test fixture
    # builders. They are intentionally ignored from the distributable source
    # manifest and recreated before the R runtime checks.
    "tests/synthetic_if_fixture/images",
    "tests/synthetic_coloc_fixture/images",
    "tests/synthetic_puncta_fixture/images",
}


def is_excluded(rel: Path) -> bool:
    if rel in EXCLUDED or rel.name == ".DS_Store":
        return True
    rel_text = rel.as_posix()
    return any(rel_text == directory or rel_text.startswith(directory + "/")
               for directory in GENERATED_DIRS)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def digest_candidates(path: Path) -> set[str]:
    data = path.read_bytes()
    candidates = {sha256_bytes(data)}

    # Git only performs line-ending conversion on text files. Treat files with
    # a NUL byte as binary and require an exact raw-byte digest for them.
    if b"\x00" in data:
        return candidates

    # Normalize all conventional line endings to LF, then also construct CRLF.
    lf = data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    crlf = lf.replace(b"\n", b"\r\n")
    candidates.add(sha256_bytes(lf))
    candidates.add(sha256_bytes(crlf))
    return candidates


def main() -> int:
    if not MANIFEST.is_file():
        print("ERROR\tmanifest\tPACKAGE_MANIFEST.sha256 is missing")
        return 1

    expected: dict[Path, str] = {}
    for line_number, line in enumerate(
        MANIFEST.read_text(encoding="utf-8").splitlines(), start=1
    ):
        if not line.strip():
            continue
        try:
            hash_value, rel = line.split("  ", 1)
        except ValueError:
            print(f"ERROR\tmanifest\tinvalid line {line_number}: {line}")
            return 1
        if len(hash_value) != 64 or any(ch not in "0123456789abcdef" for ch in hash_value.lower()):
            print(f"ERROR\tmanifest\tinvalid SHA256 on line {line_number}: {hash_value}")
            return 1
        expected[Path(rel)] = hash_value.lower()

    actual_files = {
        path.relative_to(ROOT)
        for path in ROOT.rglob("*")
        if path.is_file()
        and not is_excluded(path.relative_to(ROOT))
        and ".git" not in path.parts
    }

    missing = sorted(set(expected) - actual_files)
    unlisted = sorted(actual_files - set(expected))
    mismatched: list[Path] = []

    for rel, expected_hash in expected.items():
        path = ROOT / rel
        if path.is_file() and expected_hash not in digest_candidates(path):
            mismatched.append(rel)

    if missing or unlisted or mismatched:
        for rel in missing:
            print(f"ERROR\tmissing\t{rel}")
        for rel in unlisted:
            print(f"ERROR\tunlisted\t{rel}")
        for rel in mismatched:
            print(f"ERROR\thash_mismatch\t{rel}")
        return 1

    print(f"PASS\tmanifest\t{len(expected)} files verified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
