#!/usr/bin/env python3
"""Cross-report consistency gate for the external real-data validation bundle.

Verifies that the summary artifacts (EXTERNAL_VALIDATION_MATRIX.csv and
EXTERNAL_REALDATA_VALIDATION_REPORT.md, both generated by
external_validation/scripts/build_summary_reports.py) agree numerically with
the underlying result CSVs produced by the external validation R scripts, and
that every gate status claim matches the frozen gate rules. Any mismatch exits
non-zero so CI fails when a summary artifact drifts away from measured data.
"""
from __future__ import annotations

import csv
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "external_validation" / "results"
REPORTS = ROOT / "external_validation" / "reports"
MATRIX = ROOT / "EXTERNAL_VALIDATION_MATRIX.csv"
REPORT = ROOT / "EXTERNAL_REALDATA_VALIDATION_REPORT.md"

TOL = 1e-3

failures: list[str] = []


def fail(message: str) -> None:
    failures.append(message)


def close(a: float, b: float, tol: float = TOL) -> bool:
    return math.isfinite(a) and math.isfinite(b) and abs(a - b) <= tol


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def f(row: dict[str, str], key: str) -> float:
    return float(row[key])


def parse_gate(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"\*\*Status\*\*: \*\*([A-Z_]+)\*\*", text)
    if not match:
        fail(f"cannot parse gate status from {path.name}")
        return "UNKNOWN"
    return match.group(1)


# ---------------------------------------------------------------------------
# 1. Ground truth recomputed from the underlying result CSVs
# ---------------------------------------------------------------------------
bbbc007 = read_csv(RESULTS / "BBBC007_CELL_BOUNDARY_VALIDATION.csv")


def weighted(rows: list[dict[str, str]], value_key: str, weight_key: str) -> float:
    def ok(r: dict[str, str]) -> bool:
        return (r[value_key] not in ("", "NA", "NaN") and r[weight_key] not in ("", "NA", "NaN")
                and math.isfinite(f(r, value_key)) and math.isfinite(f(r, weight_key))
                and f(r, weight_key) > 0)

    num = sum(f(r, value_key) * f(r, weight_key) for r in rows if ok(r))
    den = sum(f(r, weight_key) for r in rows if ok(r))
    return num / den if den else float("nan")


def finite_mean(rows: list[dict[str, str]], key: str) -> float:
    values = [f(r, key) for r in rows if r[key] not in ("", "NA", "NaN") and math.isfinite(f(r, key))]
    return sum(values) / len(values) if values else float("nan")


bbbc007_metrics = {
    "nucleus_f1": finite_mean(bbbc007, "nucleus_object_f1"),
    "boundary_within_2px": weighted(bbbc007, "percent_boundary_within_2px",
                                    "relevant_pred_boundary_pixels"),
    "median_boundary_distance": finite_mean(bbbc007, "median_boundary_distance_px"),
    "overlap_pixels": sum(int(float(r["cell_mask_overlap_pixels"])) for r in bbbc007),
    "multi_nucleus_cells": sum(int(float(r["multi_nucleus_predicted_cell_count"])) for r in bbbc007),
    "zero_nucleus_cells": sum(int(float(r["zero_nucleus_predicted_cell_count"])) for r in bbbc007),
    "one_nucleus_fraction": weighted(bbbc007, "one_nucleus_per_cell_fraction", "pred_cell_count"),
}

bbbc013 = read_csv(RESULTS / "BBBC013_NC_TRANSLOCATION_SUMMARY.csv")
bbbc013_by_drug = {row["drug"]: row for row in bbbc013}
for drug in ("Wortmannin", "LY294002"):
    if drug not in bbbc013_by_drug:
        fail(f"BBBC013 summary is missing drug {drug}")
for drug, row in bbbc013_by_drug.items():
    # Frozen biology: PI3K/Akt inhibition drives FKHR into the nucleus, so the
    # N/C ratio must increase with dose and positive controls must sit above
    # negative controls.
    if f(row, "spearman_dose_response_rho") <= 0:
        fail(f"BBBC013 {drug}: dose-response rho must be positive "
             f"(cytoplasm-to-nucleus translocation)")
    if f(row, "positive_minus_negative_effect") <= 0:
        fail(f"BBBC013 {drug}: positive control must exceed negative control")
    if row["expected_direction_recovered"].strip().upper() != "TRUE":
        fail(f"BBBC013 {drug}: expected_direction_recovered must be TRUE")
    if drug == "LY294002" and row["empty_well_median_NC_ratio"] in ("", "NA"):
        fail("BBBC013: E12-H12 no-drug wells must be reported separately, not as positive controls")

bbbc016 = read_csv(RESULTS / "BBBC016_PUNCTA_EXTERNAL_SUMMARY.csv")[0]
if f(bbbc016, "spearman_puncta_per_cell") <= 0 or f(bbbc016, "spearman_integrated_intensity") <= 0:
    fail("BBBC016: dose associations must be positive")
if f(bbbc016, "maximum_dose_minus_control_effect") <= 0:
    fail("BBBC016: maximum-dose effect must be positive")

hpa_summary = read_csv(RESULTS / "HPA_IHC_SUMMARY_METRICS.csv")
hpa_overall = next((r for r in hpa_summary if r["cohort"].startswith("All Genes")), None)
if hpa_overall is None:
    fail("HPA summary is missing the 'All Genes (Overall)' cohort")
hpa_results = read_csv(RESULTS / "HPA_IHC_REALDATA_RESULTS.csv")
hpa_tiers: dict[int, dict[str, float]] = {}
for tier in (0, 1, 2, 3):
    rows = [r for r in hpa_results if int(float(r["gt_tier_num"])) == tier]
    if not rows:
        fail(f"HPA results contain no images for tier {tier}")
        continue
    hpa_tiers[tier] = {
        "n": len(rows),
        "mean_od": sum(f(r, "dab_tissue_mean_od") for r in rows) / len(rows),
        "p95_od": sum(f(r, "dab_tissue_p95_od") for r in rows) / len(rows),
        "h_score": sum(f(r, "ihc_h_score") for r in rows) / len(rows),
    }
    # keep values aligned with the generator (R na.rm behaviour is not needed here:
    # HPA result rows always carry finite metrics)
if hpa_tiers and all(t in hpa_tiers for t in (0, 1, 2, 3)):
    if not all(hpa_tiers[a]["p95_od"] < hpa_tiers[b]["p95_od"] for a, b in ((0, 1), (1, 2), (2, 3))):
        fail("HPA tier-mean P95 OD progression is not monotonically increasing")
    if not all(hpa_tiers[a]["mean_od"] < hpa_tiers[b]["mean_od"] for a, b in ((0, 1), (1, 2), (2, 3))):
        fail("HPA tier-mean OD progression is not monotonically increasing")

# ---------------------------------------------------------------------------
# 2. EXTERNAL_VALIDATION_MATRIX.csv consistency
# ---------------------------------------------------------------------------
matrix: dict[str, dict[str, str]] = {}
if not MATRIX.is_file():
    fail(f"missing file: {MATRIX}")
else:
    matrix = {row["Dataset"]: row for row in read_csv(MATRIX)}
    for expected in ("BBBC007", "BBBC013", "BBBC016", "HPA_IHC"):
        if expected not in matrix:
            fail(f"matrix is missing dataset {expected}")

    def matrix_number(dataset: str, key: str) -> float:
        text = matrix[dataset][key]
        match = re.search(r"-?\d+(?:\.\d+)?", text)
        if not match:
            fail(f"matrix {dataset}/{key} contains no number: {text!r}")
            return float("nan")
        return float(match.group())

    if "BBBC007" in matrix:
        if not close(matrix_number("BBBC007", "Primary_Metric_Value"), bbbc007_metrics["nucleus_f1"]):
            fail("matrix BBBC007 Primary_Metric_Value disagrees with BBBC007 CSV Nucleus F1")
        if not close(matrix_number("BBBC007", "Secondary_Metric_Value"), bbbc007_metrics["median_boundary_distance"]):
            fail("matrix BBBC007 Secondary_Metric_Value disagrees with BBBC007 CSV median boundary distance")
        if matrix["BBBC007"]["Gate_Status"] != "PASS_WITH_WARNINGS":
            fail("matrix BBBC007 Gate_Status must be PASS_WITH_WARNINGS")
        if matrix["BBBC007"]["Trend_Association"] != "N/A":
            fail("matrix BBBC007 Trend_Association must be N/A")
        notes = matrix["BBBC007"].get("Notes", "").lower()
        if "structural invariant" not in notes:
            fail("matrix BBBC007 Notes must reclassify overlap/one-nucleus as structural invariants by construction")

    if "BBBC013" in matrix and "Wortmannin" in bbbc013_by_drug:
        rho_w = f(bbbc013_by_drug["Wortmannin"], "spearman_dose_response_rho")
        rho_l = f(bbbc013_by_drug["LY294002"], "spearman_dose_response_rho")
        if not close(matrix_number("BBBC013", "Primary_Metric_Value"), rho_w):
            fail("matrix BBBC013 Primary_Metric_Value must equal the Wortmannin dose-response rho from the summary CSV")
        if not close(matrix_number("BBBC013", "Secondary_Metric_Value"), rho_l):
            fail("matrix BBBC013 Secondary_Metric_Value must equal the LY294002 rho from the summary CSV")
        if matrix_number("BBBC013", "Primary_Metric_Value") <= 0:
            fail("matrix BBBC013 rho must be positive (nuclear accumulation, not export)")
        if "LY294002" not in matrix["BBBC013"].get("Secondary_Metric_Name", ""):
            fail("matrix BBBC013 Secondary_Metric_Name must reference LY294002")
        if matrix["BBBC013"]["Trend_Association"] != "Positive dose association = TRUE":
            fail("matrix BBBC013 Trend_Association must be 'Positive dose association = TRUE'")
        if matrix["BBBC013"]["Gate_Status"] not in {"PASS", "PASS_WITH_WARNINGS"}:
            fail("matrix BBBC013 Gate_Status must be PASS or PASS_WITH_WARNINGS")
        notes = matrix["BBBC013"].get("Notes", "").lower()
        if "nuclear export" in notes:
            fail("matrix BBBC013 Notes must not describe nuclear export")
        if "e12-h12" not in notes:
            fail("matrix BBBC013 Notes must document the E12-H12 decoupling")

    if "BBBC016" in matrix:
        if not close(matrix_number("BBBC016", "Primary_Metric_Value"), f(bbbc016, "spearman_puncta_per_cell")):
            fail("matrix BBBC016 Primary_Metric_Value disagrees with summary CSV puncta-per-cell rho")
        if not close(matrix_number("BBBC016", "Secondary_Metric_Value"), f(bbbc016, "spearman_integrated_intensity")):
            fail("matrix BBBC016 Secondary_Metric_Value disagrees with summary CSV integrated-intensity rho")
        if matrix["BBBC016"]["Trend_Association"] != "Positive dose association = TRUE":
            fail("matrix BBBC016 Trend_Association must be 'Positive dose association = TRUE' (not Monotonic Trend)")
        if matrix["BBBC016"]["Gate_Status"] != "PASS_WITH_WARNINGS":
            fail("matrix BBBC016 Gate_Status must be PASS_WITH_WARNINGS")

    if "HPA_IHC" in matrix and hpa_overall is not None:
        if not close(matrix_number("HPA_IHC", "Primary_Metric_Value"), f(hpa_overall, "spearman_rho_p95_od")):
            fail("matrix HPA_IHC Primary_Metric_Value disagrees with HPA summary CSV P95 rho")
        if not close(matrix_number("HPA_IHC", "Secondary_Metric_Value"), f(hpa_overall, "spearman_rho_mean_od")):
            fail("matrix HPA_IHC Secondary_Metric_Value disagrees with HPA summary CSV mean-OD rho")
        if matrix["HPA_IHC"]["Gate_Status"] not in {"PASS_WITH_WARNINGS", "PASS_WITH_MAJOR_WARNINGS"}:
            fail("matrix HPA_IHC Gate_Status must be PASS_WITH_WARNINGS or PASS_WITH_MAJOR_WARNINGS")
        if not matrix["HPA_IHC"]["Trend_Association"].startswith("Monotonic tier progression"):
            fail("matrix HPA_IHC Trend_Association must describe monotonic tier progression")
        notes = matrix["HPA_IHC"].get("Notes", "")
        if "CC BY 4.0" not in notes or "CC BY-SA" in notes:
            fail("matrix HPA_IHC Notes must cite the CC BY 4.0 license")
        if "pixel-fallback" not in notes:
            fail("matrix HPA_IHC Notes must document the pixel-fallback calibration mode")
        if "pixel-level ground truth" not in notes:
            fail("matrix HPA_IHC Notes must scope the concordance away from pixel-level ground truth")

# ---------------------------------------------------------------------------
# 3. EXTERNAL_REALDATA_VALIDATION_REPORT.md consistency
# ---------------------------------------------------------------------------
if not REPORT.is_file():
    fail(f"missing file: {REPORT}")
else:
    report_text = REPORT.read_text(encoding="utf-8")

    def expect_phrase_value(pattern: str, expected: float, name: str, tol: float = TOL) -> None:
        matches = re.findall(pattern, report_text)
        if not matches:
            fail(f"report is missing the canonical phrase for {name} ({pattern!r})")
            return
        hits = [float(m) for m in matches]
        if not any(close(h, expected, tol=tol) for h in hits):
            fail(f"report {name}: found {hits} but CSV-derived value is {expected:.4f}")

    # BBBC007 section
    expect_phrase_value(r"Nucleus object F1 = (\d+\.\d+)", bbbc007_metrics["nucleus_f1"],
                        "BBBC007 Nucleus F1")
    expect_phrase_value(r"Median boundary distance \(field mean\) = (\d+\.\d+) px",
                        bbbc007_metrics["median_boundary_distance"], "BBBC007 median boundary distance")
    expect_phrase_value(r"(\d+\.\d)% within 2 px", bbbc007_metrics["boundary_within_2px"] * 100,
                        "BBBC007 boundary within 2 px", tol=0.05)
    if f"cell_mask_overlap_pixels = {bbbc007_metrics['overlap_pixels']}`)" not in report_text and \
       f"cell_mask_overlap_pixels = {bbbc007_metrics['overlap_pixels']}`" not in report_text:
        fail("report must state the BBBC007 zero-overlap structural invariant with its value")
    if "structural invariants by construction" not in report_text.lower():
        fail("report must contain the 'structural invariants by construction' classification for BBBC007")

    # BBBC013 section (positive correlations, nuclear accumulation wording)
    if "Wortmannin" in bbbc013_by_drug:
        rho_w = f(bbbc013_by_drug["Wortmannin"], "spearman_dose_response_rho")
        rho_l = f(bbbc013_by_drug["LY294002"], "spearman_dose_response_rho")
        expect_phrase_value(r"Wortmannin dose-response Spearman rho = \+(\d+\.\d+)", rho_w,
                            "BBBC013 Wortmannin rho")
        expect_phrase_value(r"LY294002 dose-response Spearman rho = \+(\d+\.\d+)", rho_l,
                            "BBBC013 LY294002 rho")
        if "-0.9760" in report_text or "-0.9120" in report_text:
            fail("report still contains the withdrawn negative BBBC013 correlations")
        low = report_text.lower()
        if "nuclear export" in low:
            fail("report must not describe BBBC013 as nuclear export")
        if "accumulat" not in low:
            fail("report must describe nuclear accumulation for BBBC013")
        if "excluded" not in low or "e12" not in low.replace("–", "-").lower():
            fail("report must document that E12-H12 are excluded from the LY294002 positive-control statistics")

    # BBBC016 section
    expect_phrase_value(r"Puncta per cell Spearman rho = (\d+\.\d+)",
                        f(bbbc016, "spearman_puncta_per_cell"), "BBBC016 puncta-per-cell rho")
    expect_phrase_value(r"Integrated puncta intensity Spearman rho = (\d+\.\d+)",
                        f(bbbc016, "spearman_integrated_intensity"), "BBBC016 integrated-intensity rho")
    if "Positive dose association" not in report_text:
        fail("report must frame BBBC016 as a positive dose association")

    # HPA section
    if hpa_overall is not None:
        expect_phrase_value(r"Overall P95 DAB OD Spearman rho = \*\*(\d+\.\d+)\*\*",
                            f(hpa_overall, "spearman_rho_p95_od"), "HPA overall P95 rho")
        expect_phrase_value(r"Overall mean DAB OD Spearman rho = \*\*(\d+\.\d+)\*\*",
                            f(hpa_overall, "spearman_rho_mean_od"), "HPA overall mean-OD rho")
        expect_phrase_value(r"Overall H-Score \(0–300\) Spearman rho = \*\*(\d+\.\d+)\*\*",
                            f(hpa_overall, "spearman_rho_h_score"), "HPA overall H-Score rho")
        for gene in ("EPCAM", "KRT20", "PAX8", "ESR1"):
            row = next((r for r in hpa_summary if r["cohort"] == f"Gene: {gene}"), None)
            if row is None:
                fail(f"HPA summary is missing gene {gene}")
                continue
            expect_phrase_value(gene + r" \(`(\d+\.\d+)`\)", f(row, "spearman_rho_p95_od"),
                                f"HPA {gene} P95 rho")
        for tier in (0, 1, 2, 3):
            if tier in hpa_tiers:
                labels = {0: "0 - Not detected", 1: "1 - Low", 2: "2 - Medium", 3: "3 - High"}
                row_pattern = re.escape(f"| **{labels[tier]}** | {hpa_tiers[tier]['n']} | ") + \
                    r"(\d+\.\d+) \| (\d+\.\d+) \| (\d+\.\d) \|"
                match = re.search(row_pattern, report_text)
                if not match:
                    fail(f"report is missing the HPA tier row for {labels[tier]}")
                else:
                    vals = (float(match.group(1)), float(match.group(2)), float(match.group(3)))
                    expected = (hpa_tiers[tier]["mean_od"], hpa_tiers[tier]["p95_od"], hpa_tiers[tier]["h_score"])
                    if not all(close(v, e, tol=0.05) for v, e in zip(vals, expected)):
                        fail(f"report HPA tier {tier} row {vals} disagrees with CSV-derived {expected}")

    # Gate statuses: the report must carry each dataset's gate from its specialized report
    statuses = {
        "BBBC007": parse_gate(REPORTS / "BBBC007_CELL_BOUNDARY_VALIDATION_REPORT.md"),
        "BBBC013": parse_gate(REPORTS / "BBBC013_NC_TRANSLOCATION_VALIDATION.md"),
        "BBBC016": bbbc016["status"],
        "HPA IHC": parse_gate(REPORTS / "HPA_IHC_EXTERNAL_VALIDATION.md"),
    }
    section_keys = {"BBBC007": "BBBC007", "BBBC013": "BBBC013", "BBBC016": "BBBC016",
                    "HPA IHC": "Human Protein Atlas"}
    for dataset, status in statuses.items():
        # Section-scoped check: the dataset subsection's gate line must match.
        section = re.search(
            r"### 3\.\d [^\n]*" + re.escape(section_keys[dataset]) + r"[^\n]*\n(.*?)(?=\n### |\n---)",
            report_text, flags=re.DOTALL,
        )
        if section is None:
            fail(f"report is missing dataset section {dataset}")
            continue
        if f"**Gate status**: **{status}**" not in section.group(1):
            fail(f"report gate line for {dataset} does not match its specialized report status {status}")

# ---------------------------------------------------------------------------
# 4. Terminology, HPA wording, and release-metadata guards
# ---------------------------------------------------------------------------
# A. IF fluorescence intensity must never be labelled "OD" (optical density is
#    a brightfield/transmitted-light concept). DAB OD usage is unaffected: the
#    patterns below only fire when "OD" co-occurs with a puncta/fluorescence
#    context in the same sentence fragment.
if_od_pattern = re.compile(
    r"puncta[^.\n]*\bOD\b|\bOD\b[^.\n]*puncta|fluorescence\s+od",
    re.IGNORECASE,
)
guard_targets = [MATRIX, REPORT, ROOT / "README.md", ROOT / "README_EN.md"]
guard_targets += sorted(REPORTS.glob("*.md"))
for target in guard_targets:
    if not target.is_file():
        continue
    text = target.read_text(encoding="utf-8")
    for match in if_od_pattern.finditer(text):
        line_no = text[: match.start()].count("\n") + 1
        fail(f"IF terminology guard: {target.name}:{line_no} labels a fluorescence "
             f"puncta metric as 'OD' ({match.group(0).strip()!r}); use 'intensity' "
             f"(brightfield DAB OD is unaffected)")

# B. HPA wording guards: no over-claims, no hidden weak markers.
banned_phrases = ("all endpoints are scale-invariant", "correlate strongly and monotonically")
for target in guard_targets:
    if not target.is_file():
        continue
    low = target.read_text(encoding="utf-8").lower()
    for phrase in banned_phrases:
        if phrase in low:
            fail(f"HPA wording guard: {target.name} contains banned over-claim {phrase!r}")

hpa_section = re.search(
    r"### 3\.\d [^\n]*Human Protein Atlas[^\n]*\n(.*?)(?=\n### |\n---)",
    report_text if REPORT.is_file() else "",
    flags=re.DOTALL,
)
if hpa_section is None:
    fail("report is missing the HPA section for wording guards")
else:
    hpa_text = hpa_section.group(1).lower()
    for phrase in (
        "moderate-to-strong ordinal concordance",
        "marker-specific heterogeneity",
        "pixel-fallback",
        "cc by 4.0",
        "qualitative",
        "not a diagnostic validation",
    ):
        if phrase not in hpa_text:
            fail(f"HPA wording guard: report HPA section must state {phrase!r}")
    if "esr1" not in hpa_text:
        fail("HPA wording guard: the weak ESR1 result must remain visible in the report")

# C. Release metadata: README release badges must match VERSION.
version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
badge_label = f"release-v{version.replace('-', '--')}-blue"
for name in ("README.md", "README_EN.md"):
    badge_path = ROOT / name
    if not badge_path.is_file():
        fail(f"release metadata guard: {name} is missing")
        continue
    badge_text = badge_path.read_text(encoding="utf-8")
    if badge_label not in badge_text:
        fail(f"release metadata guard: {name} release badge does not show VERSION {version}")
    if f"/releases/tag/v{version}" not in badge_text and f"/releases/tag/{version}" not in badge_text:
        fail(f"release metadata guard: {name} release badge does not link to the {version} release tag")

# ---------------------------------------------------------------------------
if failures:
    print("FAIL\treport-consistency")
    for item in failures:
        print(f"ERROR\t{item}")
    sys.exit(1)

print("PASS\treport-consistency\tmatrix, report, and result CSVs agree")
